module.exports = {
  INVALID_INPUT: "INVALID_INPUT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INVALID_OPTIONS: "INVALID_OPTIONS",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  INVALID_DISCOUNT: "INVALID_DISCOUNT"
};
