export const COPY = {
  en: {
    title: "Which one is worth it?",
    subtitle: "Helps when you're unsure between options.",
    addOption: "+ Add another choice",
    calculate: "See which is better",
    price: "Price (฿)",
    size: "How much do you get?",
    unit: "Unit",
    deal: "Deal (optional)",
    resultTitle: "Here’s what makes more sense:",
    best: "This choice gives you more for your money.",
    history: "Past comparisons",
  },
  th: {
    title: "อันไหนคุ้มกว่ากัน?",
    subtitle: "ช่วยตัดสินใจเวลาเลือกไม่ถูก",
    addOption: "+ เพิ่มตัวเลือก",
    calculate: "ดูว่าอันไหนคุ้มกว่า",
    price: "ราคา (บาท)",
    size: "ปริมาณที่ได้",
    unit: "หน่วย",
    deal: "โปร (ไม่บังคับ)",
    resultTitle: "สรุปแบบเข้าใจง่าย:",
    best: "ตัวเลือกนี้คุ้มค่าที่สุด",
    history: "การเปรียบเทียบที่ผ่านมา",
  },
};
